[book]
authors = ["emanuele-em"]
language = "en"
multilingual = false
src = "src"
title = "Competitive Programmer's Handbook - Rust Edition"

[output.html]
additional-css = ["assets/css/custom.css"]
mathjax-support = true

[preprocessor.katex]
[preprocessor.graphviz]
command = "mdbook-graphviz"
